#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#Prompt for kerberos password if not logged in
if type klist > /dev/null; then
    while ! `klist > /dev/null 2>&1`; do kinit; done; aklog
fi
fortune
