"A vimrc from scratch, which contains bits of different people's configs,
"plus bits of spf-13 that I like. In time I will probably split it out into
"multiple files
"
"The config assumes that you are running Vim 7.4 (or a recent-ish version of
"7.3) on Linux in a terminal, this will probably break things in other 
"environments

set nocompatible
set encoding=utf-8
filetype off

set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

"Map leader key to comma
let mapleader=","
let g:mapleader=","

Plugin 'gmarik/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'tmhedberg/matchit'
Plugin 'tomasr/molokai'
Plugin 'Valloric/YouCompleteMe'
Plugin 'Shougo/unite.vim'
Plugin 'Shougo/vimfiler.vim'
Plugin 'Shougo/vimproc.vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-fugitive'
Plugin 'JuliaLang/julia-vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'sheerun/vim-polyglot'
"Plugin 'greyblake/vim-preview'
"Plugin 'terryma/vim-multiple-cursors'
"Plugin 'scrooloose/nerdcommenter'
"Plugin 'tpope/vim-surround'

call vundle#end()

filetype plugin indent on
set expandtab
set ts=4
set sw=4
set softtabstop=4
set shiftround
set cc=80
set t_vb=
set history=1000
set tabpagemax=50

set number
set cursorline
set laststatus=2
syntax enable
"au BufNewFile,BufRead,BufEnter *.txt setlocal spell spelllang=en_ie
"Show the current mode and command in the status bar
set showmode
set showcmd
set backspace=indent,eol,start
"Auto reload file if it has been changed elsewhere
set autoread
set viminfo^=!

"Search options, do incremental search and highlight results
set incsearch
set hlsearch

"Get rid of swap files
set nobackup
set noswapfile
set nowb

"Terminal stuff, set window title, disable any bells, turn on ALL the colours
set title
set novisualbell
set noerrorbells
set t_Co=256

"Command auto-complete menu
set wildmenu
set wildmode=longest:list,full

"Note: Lazyredraw and airline do not work well together
"set lazyredraw
"Turn on mouse integration
set mouse=a
set ttyfast
"Case insensitive searching
set ignorecase
"Regex magic
set magic
"Use blowfish for encryption
set cm=blowfish
set nofoldenable

"`vsplit` to the right, `split` new windows below the current one
set splitright
set splitbelow

"Highlight spaces, tabs, etc
set list
set listchars=tab:›\ ,trail:•,extends:#,nbsp:.

set timeoutlen=1000
set ttimeoutlen=0

"Integrate with OS clipboard
set clipboard=unnamedplus

nmap <leader>w :w!<cr>
nmap <leader>q :q!<cr>

"Ooh, pretty colours...
set background=dark
let g:molokai_original = 1
let g:rehash256 = 1
colorscheme molokai
colors molokai

"Powerline settings
let g:airline_theme='powerlineish'
let g:airline_powerline_fonts=1

"Use vimfiler as the default browser
let g:vimfiler_as_default_explorer=1

"Close YCM's preview window automatically
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_autoclose_preview_window_after_completion = 1
"let g:ycm_collect_identifiers_from_tags_files=1

"An amusing experiment in masochism
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>
