set encoding=utf-8
set nocompatible
set background=dark
filetype off

set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-sensible'
Plugin 'Shougo/neocomplete.vim'
Plugin 'bling/vim-airline'
Plugin 'tmhedberg/matchit'
Plugin 'altercation/vim-colors-solarized'
Plugin 'flazz/vim-colorschemes'
Plugin 'tomasr/molokai'

call vundle#end()

filetype plugin indent on
set expandtab
set ts=4
set sw=4
set softtabstop=4
set shiftround
set tw=80
set t_vb=
set history=1000
set tabpagemax=50

set number
set cursorline
syntax enable
"au BufNewFile,BufRead,BufEnter *.txt setlocal spell spelllang=en_ie
set showmode
set showcmd
set backspace=indent,eol,start
set autoread
set viminfo^=!

"set ruler                   " Show the ruler
"set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%) " A ruler on steroids
"Search options, do incremental search and highlight results
set incsearch
set hlsearch

"Get rid of swap files
set nobackup
set noswapfile
set nowb

"Terminal stuff, set window title, disable any bells, turn on ALL the colours
set title
set novisualbell
set noerrorbells
set t_Co=256

"Command auto-complete menu
set wildmenu
set wildmode=longest,full

"Note: Lazyredraw and airline do not work well together
"set lazyredraw
set mouse=a
set ttyfast
set ignorecase
set magic
set cm=blowfish
set nofoldenable

"Highlight spaces, tabs, etc
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.

set timeoutlen=0
"Integrate with OS clipboard
set clipboard=unnamedplus

let mapleader=","
let g:mapleader=","
nmap <leader>w :w!<cr>
nnoremap <silent> ,/ :nohlsearch<CR>
colorscheme molokai
colors molokai
let g:airline_theme='powerlineish'
let g:airline_powerline_fonts=1
